 -- 코드를 입력하세요 ANIMAL_INS TIME  = 보호 시작일,  ANIMAL_OUTS TIME : 입양일
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME;
