-- 코드를 입력하세요
-- USED_GOODS_BOARD : 중고 거래 게시판 정보
-- USED_GOODS_REPLY  : 중고거래 게시판 첨부파일 정보 담은 테이블
SELECT 
    B.TITLE, 
    B.BOARD_ID, 
    R.REPLY_ID, 
    R.WRITER_ID, 
    R.CONTENTS, 
    DATE_FORMAT(R.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS B  
    JOIN USED_GOODS_REPLY AS R 
    ON B.BOARD_ID = R.BOARD_ID 
WHERE B.CREATED_DATE like '2022-10%'
ORDER BY R.CREATED_DATE ASC,  B.TITLE ASC;
